package cdkmonitoringconstructs

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/corymhall/cdk-constructs-go/cdkmonitoringconstructs/jsii"
)

// Experimental.
type AlarmNamingStrategy interface {
	IAlarmNamingStrategy
	// Experimental.
	DedupeStringStrategy() IAlarmDedupeStringProcessor
	// Experimental.
	GlobalPrefix() *string
	// Experimental.
	LocalPrefix() *string
	// Dedupe string resolved like this: - If "dedupeStringOverride" is defined for an alarm, it will be used as a dedupe string.
	//
	// - If "alarmDedupeStringSuffix" from the alarm factory is defined, "GlobalPrefix-LocalPrefix-AlarmDedupeStringSuffix" will be used as a dedupe string.
	// - Otherwise, the alarm dedupe string will not be set.
	// If a dedupe string strategy is set, it will be used to process the final string.
	// Experimental.
	GetDedupeString(props *AlarmNamingInput) *string
	// Alarm name is resolved like this: - If "alarmNameOverride" is defined for an alarm, it will be used as alarm name.
	//
	// - Otherwise, the alarm name will be generated by joining: global prefix, local prefix, alarm name suffix, disambiguator.
	// Experimental.
	GetName(props *AlarmNamingInput) *string
	// How to generate the label for the alarm displayed on a widget.
	// Experimental.
	GetWidgetLabel(props *AlarmNamingInput) *string
	// Experimental.
	JoinDistinct(parts *[]*string, separator *string) *string
}

// The jsii proxy struct for AlarmNamingStrategy
type jsiiProxy_AlarmNamingStrategy struct {
	jsiiProxy_IAlarmNamingStrategy
}

func (j *jsiiProxy_AlarmNamingStrategy) DedupeStringStrategy() IAlarmDedupeStringProcessor {
	var returns IAlarmDedupeStringProcessor
	_jsii_.Get(
		j,
		"dedupeStringStrategy",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AlarmNamingStrategy) GlobalPrefix() *string {
	var returns *string
	_jsii_.Get(
		j,
		"globalPrefix",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_AlarmNamingStrategy) LocalPrefix() *string {
	var returns *string
	_jsii_.Get(
		j,
		"localPrefix",
		&returns,
	)
	return returns
}


// Experimental.
func NewAlarmNamingStrategy(globalPrefix *string, localPrefix *string, dedupeStringStrategy IAlarmDedupeStringProcessor) AlarmNamingStrategy {
	_init_.Initialize()

	if err := validateNewAlarmNamingStrategyParameters(globalPrefix, localPrefix); err != nil {
		panic(err)
	}
	j := jsiiProxy_AlarmNamingStrategy{}

	_jsii_.Create(
		"cdk-monitoring-constructs.AlarmNamingStrategy",
		[]interface{}{globalPrefix, localPrefix, dedupeStringStrategy},
		&j,
	)

	return &j
}

// Experimental.
func NewAlarmNamingStrategy_Override(a AlarmNamingStrategy, globalPrefix *string, localPrefix *string, dedupeStringStrategy IAlarmDedupeStringProcessor) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-monitoring-constructs.AlarmNamingStrategy",
		[]interface{}{globalPrefix, localPrefix, dedupeStringStrategy},
		a,
	)
}

func (a *jsiiProxy_AlarmNamingStrategy) GetDedupeString(props *AlarmNamingInput) *string {
	if err := a.validateGetDedupeStringParameters(props); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getDedupeString",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AlarmNamingStrategy) GetName(props *AlarmNamingInput) *string {
	if err := a.validateGetNameParameters(props); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getName",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AlarmNamingStrategy) GetWidgetLabel(props *AlarmNamingInput) *string {
	if err := a.validateGetWidgetLabelParameters(props); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getWidgetLabel",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_AlarmNamingStrategy) JoinDistinct(parts *[]*string, separator *string) *string {
	if err := a.validateJoinDistinctParameters(parts, separator); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"joinDistinct",
		[]interface{}{parts, separator},
		&returns,
	)

	return returns
}

