package cdkmonitoringconstructs

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/corymhall/cdk-constructs-go/cdkmonitoringconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/corymhall/cdk-constructs-go/cdkmonitoringconstructs/internal"
)

// Specific subtype of dashboard that renders supported widgets as bitmaps, while preserving the overall layout.
// Experimental.
type BitmapDashboard interface {
	awscloudwatch.Dashboard
	// Experimental.
	BitmapRenderingSupport() BitmapWidgetRenderingSupport
	// ARN of this dashboard.
	// Experimental.
	DashboardArn() *string
	// The name of this dashboard.
	// Experimental.
	DashboardName() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Add a variable to the dashboard.
	// See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_dashboard_variables.html
	//
	// Experimental.
	AddVariable(variable awscloudwatch.IVariable)
	// Add a widget to the dashboard.
	//
	// Widgets given in multiple calls to add() will be laid out stacked on
	// top of each other.
	//
	// Multiple widgets added in the same call to add() will be laid out next
	// to each other.
	// Experimental.
	AddWidgets(widgets ...awscloudwatch.IWidget)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	AsBitmap(widget awscloudwatch.IWidget) awscloudwatch.IWidget
	// Experimental.
	AsBitmaps(widgets ...awscloudwatch.IWidget) *[]awscloudwatch.IWidget
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for BitmapDashboard
type jsiiProxy_BitmapDashboard struct {
	internal.Type__awscloudwatchDashboard
}

func (j *jsiiProxy_BitmapDashboard) BitmapRenderingSupport() BitmapWidgetRenderingSupport {
	var returns BitmapWidgetRenderingSupport
	_jsii_.Get(
		j,
		"bitmapRenderingSupport",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) DashboardArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"dashboardArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) DashboardName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"dashboardName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BitmapDashboard) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewBitmapDashboard(scope constructs.Construct, id *string, props *awscloudwatch.DashboardProps) BitmapDashboard {
	_init_.Initialize()

	if err := validateNewBitmapDashboardParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_BitmapDashboard{}

	_jsii_.Create(
		"cdk-monitoring-constructs.BitmapDashboard",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewBitmapDashboard_Override(b BitmapDashboard, scope constructs.Construct, id *string, props *awscloudwatch.DashboardProps) {
	_init_.Initialize()

	_jsii_.Create(
		"cdk-monitoring-constructs.BitmapDashboard",
		[]interface{}{scope, id, props},
		b,
	)
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func BitmapDashboard_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateBitmapDashboard_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-monitoring-constructs.BitmapDashboard",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func BitmapDashboard_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateBitmapDashboard_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-monitoring-constructs.BitmapDashboard",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func BitmapDashboard_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateBitmapDashboard_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"cdk-monitoring-constructs.BitmapDashboard",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) AddVariable(variable awscloudwatch.IVariable) {
	if err := b.validateAddVariableParameters(variable); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addVariable",
		[]interface{}{variable},
	)
}

func (b *jsiiProxy_BitmapDashboard) AddWidgets(widgets ...awscloudwatch.IWidget) {
	args := []interface{}{}
	for _, a := range widgets {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		b,
		"addWidgets",
		args,
	)
}

func (b *jsiiProxy_BitmapDashboard) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := b.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (b *jsiiProxy_BitmapDashboard) AsBitmap(widget awscloudwatch.IWidget) awscloudwatch.IWidget {
	if err := b.validateAsBitmapParameters(widget); err != nil {
		panic(err)
	}
	var returns awscloudwatch.IWidget

	_jsii_.Invoke(
		b,
		"asBitmap",
		[]interface{}{widget},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) AsBitmaps(widgets ...awscloudwatch.IWidget) *[]awscloudwatch.IWidget {
	args := []interface{}{}
	for _, a := range widgets {
		args = append(args, a)
	}

	var returns *[]awscloudwatch.IWidget

	_jsii_.Invoke(
		b,
		"asBitmaps",
		args,
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := b.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		b,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) GetResourceNameAttribute(nameAttr *string) *string {
	if err := b.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		b,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BitmapDashboard) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

